# Generated by Django 4.1.7 on 2023-04-05 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iss', '0003_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
